local_webkitmm_lib = $(top_builddir)/webkit/webkitmm/libwebkitmm-1.0.la

LIBS  = $(local_webkitmm_lib) $(WEBKITMM_LIBS)

all_includes = -I$(top_builddir)/webkit -I$(top_srcdir)/webkit \
               $(WEBKITMM_CFLAGS)
                     
DEFS = @DEFS@
DEFAULT_INCLUDES =
INCLUDES = -I. -I$(srcdir) $(strip $(all_includes))

